#!/usr/bin/env bash
# Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw app list
sudo ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.html
sudo service nginx restart

