#!/usr/bin/env bash
# Redirect configuration

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'

new_page="https://www.youtube.com/watch?v=QH2-TGUlwu4"
file="/etc/nginx/sites-available/default"
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me $new_page permanent;" $file

sudo service nginx restart

