#!/usr/bin/env bash
# Configure HAproxy

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

path="/etc/haproxy/haproxy.cfg"
echo "
frontend http
	bind *:80
	mode http
	default_backend icap_pool
backend icap_pool
	balance roundrobin
	mode http
	server 3332-web-01 3.93.164.52:80 check
	server 3332-web-02 18.207.92.226:80 check" | sudo tee -a $path > /dev/null

sudo service haproxy start
sudo service nginx restart

