#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd
FILE="/etc/passwd"
while IFS=: read -r username _ userid _ _ homedir _
do
    echo "$username:$userid:$homedir"
done < $FILE