#!/usr/bin/env bash
# this script displays the numbers from 1 to 20, depending on the case it displays a special message
counter=1

while [ $counter -le 20 ]
do
    echo $counter

    case $counter in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
    esac

    ((counter++))
done